In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:6])

[1 2 3 4 5 6]
